### ISSUE TITLE
typings/express/express.d.ts not found in Server folder

### ISSUE THREAD

**Issue by tanvirastogi08** [Anjmao/angular2-dogeapp#1]
Hi,

     When running the command **gulp start-server** in the code, the following error is thrown 
![image](https://user-images.githubusercontent.com/17062049/39512442-a52e5fcc-4e0e-11e8-9fdb-5e05cd81ad67.png)
In server/typings/body-parser/body-parser.d.ts
/// <reference path="../express/express.d.ts" /> says  "../express/express.d.ts" not found as there is no express folder at the path typings/express/
        Please share the solution to this problem.

Thanks!

**Comment by tanvirastogi08** [comment]
Resolved the issue by deleting the typings folder and simply running command

**Comment by tanvirastogi08** [comment]
I have deleted the typings folder and instead of gulp start-server run the command node app as follows:
angular2-dogeapp\server>node app 

Created the DB in pgAdmin 4 named 'candy-fun' as I was getting the following error:

Node app is running on port 5000
Unhandled rejection SequelizeConnectionError: database "candy-fun" does not exist
    at F:\tanvi\angular2-dogeapp\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:133:20
    at Connection.<anonymous> (F:\tanvi\angular2-dogeapp\node_modules\pg\lib\client.js:176:5)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (F:\tanvi\angular2-dogeapp\node_modules\pg\lib\connection.js:109:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)

Run the code again using:
angular2-dogeapp\server>node app

The code runs successfully!

Thanks for the sample. It's really helpful!
